### ISSUE TITLE
BUG_UnhandledPromiseRejectionWarning: DataCloneError: eventName

### ISSUE THREAD

**Issue by chamikabm** [pioardi/poolifier#308] opened 2021-04-08 09:43 UTC
**Describe the bug**
I tried to create Fixed and Dynamic ThreadPools as follows and try to pass the mongo db instance to the worker. It throws an error as follows:

```
api      |     Merkle Root: 0x29711e9454dc2c1d629c0cdc0b0924d762db96cd86b3702c4af32b71469e2fa8
api      | (node:21) UnhandledPromiseRejectionWarning: DataCloneError: eventName => {
api      |     if (DEPRECATED_UNIFIED_EVENTS.has(eventName)) {
api      |       emitDeprecationWarning(
api      |         `The \...<omitted>... } could not be cloned.
api      |     at Worker.postMessage (internal/worker.js:223:23)
api      |     at g.sendToWorker (/usr/api/node_modules/poolifier/lib/index.js:1:5850)
api      |     at g.execute (/usr/api/node_modules/poolifier/lib/index.js:1:3871)
api      |     at sendCredentialIssuedEmail (/usr/api/src/email/sendCredentialIssuedEmail.js:85:14)
api      |     at Server.issueAndPublishCertificates (/usr/api/src/routes/issuer.js:282:5)
api      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
api      | (node:21) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
api      | (node:21) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

Using Cluster Fixed Pool gave following issue :

```
api      |     Merkle Root: 0x211155733b5f5bd5e88f99c833fb0c95917aa6fd7d4bb51cb5e2b443acb05590
api      | (node:19) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
api      |     --> starting at object with constructor 'NativeTopology'
api      |     |     property 's' -> object with constructor 'Object'
api      |     |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
api      |     --- property 'topology' closes the circle
api      |     at JSON.stringify (<anonymous>)
api      |     at ChildProcess.target._send (internal/child_process.js:778:25)
api      |     at ChildProcess.target.send (internal/child_process.js:676:19)
api      |     at Worker.send (internal/cluster/worker.js:43:28)
api      |     at y.sendToWorker (/usr/api/node_modules/poolifier/lib/index.js:1:5413)
api      |     at y.execute (/usr/api/node_modules/poolifier/lib/index.js:1:3871)
api      |     at sendCredentialIssuedEmail (/usr/api/src/email/sendCredentialIssuedEmail.js:85:14)
api      |     at Server.issueAndPublishCertificates (/usr/api/src/routes/issuer.js:282:5)
api      |     at processTicksAndRejections (internal/process/task_queues.js:93:5)
api      | (node:19) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
api      | (node:19) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to reproduce the behavior**

```
    const workerScript = path.join(__dirname, './yourWorker.js');
    const pool = new FixedThreadPool(15,
        workerScript,
        { errorHandler: (e) => console.error(e), onlineHandler: () => console.log('worker is online') })

    let resolved = 0
    const start = Date.now()
    const certsCount = _.size(issuedCerts);
    for (const issuedCert of issuedCerts) {
        pool
            .execute({
                cert: issuedCert,
                db,
            })
            .then(res => {
                resolved++
                if (resolved === certsCount) {
                    return console.log('Time take is ' + (Date.now() - start))
                }
                return null
            })
            .catch(err => console.error(err));
    }
```

**Info**

| Tool      | Version       |
| --------- | ------------- |
| Poolifier | v2.0.1        |
| Node      | v node:12.13.1-stretch  - Docker      |
| OS        | linux - Debian - Docker |

**Additional context**
> Worker is an async task processor
> Tried both Fixed and Dynamic Pools

**Comment by pioardi** [comment] 2021-04-08 13:06
Hi @chamikabm nice to meet you and thanks to use poolifier.
As per node.js documentation you can only pass serializable data from the main process to the worker threads.
I think this is the main issue here, you could try to have one mongodb client instance per thread ,but my suggestion is to avoid I/O operations ( like write/read from a database ) into worker threads since they are particurally useful for CPU tasks.
You can try to split your tasks in two/three and only do CPU stuff in worker threads, or in alternative try to instantiate the mongodb client into the worker thread directly.


Hope this helps

**Comment by pioardi** [comment] 2021-04-08 13:08
CC: @Shinigami92 @jerome-benoit

**Comment by chamikabm** [comment] 2021-04-08 14:20
@pioardi Thanks for the update. My problem here is I have both CPI and I/O related in the same function which can't be split into few tasks. They have to be serial. That's why I was testing both the Thread and Cluster Pools, So my plan was to do a load test around both pool systems and use the best out of each. So as you suggested, if I create a DB instance inside the worker will be reuse across all the queued items? For example, if I create a Fixed Thread Pool with 10 workers and then if submit 1000 tasks to the pool for the execution, then there will only be 10 instances of MongoDB using inside all the workers(i.e One instance per one worker ) is it ? I'm kind of new to these workers and cluster concepts. Please be sorry for asking these questions.

**Comment by pioardi** [comment] 2021-04-08 14:49
@chamikabm  so even if you split the function into 2/3 pieces you can still get serial execution doing the things in the right order and use async/await construct properly.

To answer your question yes you could write a worker.js like this:

`
const mondodbclient = require('').dostuff

function yourLogic () {
 // use mongodb client here
}

module.exports = new ThreadWorker(yourLogic , {
  maxInactiveTime: 60000,
  async: false/true
})
`

In this way the mongodbclient should be accessible within the function is just a js closure I guess this should work, would you try and let me know ? :)

Hope this helps

**Comment by chamikabm** [comment] 2021-04-09 16:28
@pioardi  This is what exactly that I have been trying.

```
// MongoDb.js
const {
    MongoClient,
} = require('mongodb');
const {
    MongoMemoryServer,
} = require('mongodb-memory-server');
const {
    DB_URL,
} = require('../constants');

class MongoDb {
    constructor() {
        if (!MongoDb.instance) {
            this.properties = {};

            console.log('#### Return MongoDb New Instance')
            MongoDb.instance = this;
        }

        console.log('#### Return MongoDb Existing Instance')
        return MongoDb.instance;
    }

    async getConnection () {
        try {
            console.log('##### Existing mongo connection not found, Hence going to create new connection.');
            if (!this.properties['connection']) {
                let mongoUrl;
                if (!DB_URL) {
                    console.log('DB URL not found, Hence using in memory mongodb.');
                    const mongo = new MongoMemoryServer();
                    mongoUrl = await mongo.getConnectionString();
                } else {
                    console.log('DB URL found, Hence using the given DB_URL : '. DB_URL);
                    mongoUrl = DB_URL;
                }

                console.log('Going to create the mongo DB connection with URL : ', mongoUrl);
                const connection = await MongoClient.connect(mongoUrl, {
                    useNewUrlParser: true,
                    useUnifiedTopology: true,
                });

                console.log('##### Returning newly created mongo connection');
                this.properties['connection'] = connection;
                return connection;
            } else {

                console.log('##### Returning existing mongo connection');
                return this.properties['connection'];
            }
        } catch (err) {
            console.log('Something went wrong while creating the DB connection. Error : ', err);
        }
    }
}

const instance = new MongoDb();
Object.freeze(instance);

module.exports = instance;
```

```
// myPool.js
const {
    FixedThreadPool,
} = require('poolifier')
async function sendCredentialIssuedEmail(issuedCerts) {
    const workerScript = path.join(__dirname, './yourWorker.js');
    const pool = new FixedThreadPool(5,
        workerScript,
        { errorHandler: (e) => console.error(e), onlineHandler: () => console.log('worker is online') })

    let resolved = 0;
    const start = Date.now();
    for (const issuedCert of issuedCerts) {
        pool
            .execute({
                cert: 'issuedCert',
            })
            .then(res => {
                resolved++;
                if (resolved === certsCount) {
                    return console.log('Time take is ' + (Date.now() - start));
                }

                return null;
            })
            .catch(err => console.error(err));
    }
}

module.exports = {
    sendCredentialIssuedEmail,
}
```

```
// yourWorker.js
const yourFunction = async (data) => {
    console.log('yourFunction start. data : ', data)

    await MongoDb.getConnection();
    console.log('yourFunction end data : ', data)
    return { ok: 1 };
}

module.exports = new ThreadWorker(yourFunction, {
    async: true,
})
```

This is my existing setup, But each time I submit a task to the pool it creates a new Mongo DB connection. Please be kind enough to explaining to me what I'm doing wrong here. Thanks :) Following is the output that I get for each worker running with all tasks.

```
Going to create the mongo DB connection with URL :  mongodb://127.0.0.1:58705/ae072e4a-178f-4974-ade3-7159197db089
##### Returning newly created mongo connection
```

**Comment by pioardi** [comment] 2021-04-10 10:22
Thanks @chamikabm  for the update, so the issue is basically resolved.
If you agree I would close this issue.

**Comment by chamikabm** [comment] 2021-04-11 09:56
@pioardi Yes, it is resolved. Thanks for being helpful! And for this awesome library. Looking forward to seeing more features. Cheers!

**Closed** 2021-04-11 10:12 UTC
Labels: help wanted
